from __future__ import annotations
import pandas as pd
import pytest
from unittest.mock import MagicMock, patch
from inti_intelligence.snowflake_db import load_catalog_from_snowflake, save_catalog_to_snowflake
from inti_intelligence.cortex_intelligence import get_cortex_executive_summary

def test_load_catalog_from_snowflake_empty_when_no_active_session():
    # If credentials are not set, it should handle failure and return empty df
    with patch("inti_intelligence.snowflake_db.get_snowflake_session", side_effect=ValueError("No session")):
        df = load_catalog_from_snowflake()
        assert isinstance(df, pd.DataFrame)
        assert df.empty

def test_load_catalog_from_snowflake_mocked(monkeypatch):
    mock_session = MagicMock()
    # Mocking check for table exists
    mock_session.sql.return_value.collect.return_value = [{"name": "PRODUCT_VARIANTS"}]
    
    mock_df = pd.DataFrame({
        "product_id": ["sf-1"],
        "name": ["Vestido Snowflake"],
        "url": ["https://snowflake.com/1"]
    })
    
    mock_snowpark_df = MagicMock()
    mock_snowpark_df.to_pandas.return_value = mock_df
    mock_session.table.return_value = mock_snowpark_df

    # Force get_snowflake_session to return our mock session
    with patch("inti_intelligence.snowflake_db.get_snowflake_session", return_value=mock_session):
        df = load_catalog_from_snowflake()
        assert not df.empty
        assert len(df) == 1
        assert df["name"].iloc[0] == "Vestido Snowflake"

def test_save_catalog_to_snowflake_mocked():
    mock_session = MagicMock()
    mock_session.get_current_warehouse.return_value = "TEST_WH"
    
    test_df = pd.DataFrame({
        "product_id": ["sf-2"],
        "name": ["Prod SF"],
        "url": ["http://sf"]
    })

    with patch("inti_intelligence.snowflake_db.get_snowflake_session", return_value=mock_session):
        save_catalog_to_snowflake(test_df)
        # Should verify write pipeline is called
        assert mock_session.create_dataframe.called
        assert mock_session.create_dataframe.return_value.write.mode.called
        assert mock_session.create_dataframe.return_value.write.mode.return_value.save_as_table.called

def test_cortex_executive_summary_mocked():
    mock_session = MagicMock()
    # Mocking response of SELECT SNOWFLAKE.CORTEX.COMPLETE(...)
    mock_session.sql.return_value.collect.return_value = [{"RESPONSE": "Summary generated by Snowflake Llama3."}]
    
    test_df = pd.DataFrame({
        "product_id": ["sf-3"],
        "category": ["Blusas"],
        "discount_pct": [0.15]
    })
    
    with patch("inti_intelligence.cortex_intelligence.get_snowflake_session", return_value=mock_session):
        summary = get_cortex_executive_summary(test_df, 5, 2)
        assert "Snowflake Llama3" in summary
